[build]
  base = "client"
  command = "CI=false npm ci && CI=false npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", CI = "false" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 